version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package -Pprod -DskipTests
  post_build:
    commands:
      - echo Build complete.
artifacts:
  base-directory: target
  files:
    - copilot-backend-0.0.1-SNAPSHOT.jar
  discard-paths: yes
