assemblyai.api-key=${ASSEMBLY_AI_API_KEY:}
openai.api-key=${OPENAI_API_KEY:}
app.cors.deployed-origin=${APP_CORS_DEPLOYED_ORIGIN:}

aws.cognito.region=${AWS_REGION:}
aws.cognito.user-pool-id=${AWS_USER_POOL:}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
