assemblyai.api-key=${ASSEMBLY_AI_API_KEY:}
openai.api-key=${OPENAI_API_KEY:}
app.cors.deployed-origin=${APP_CORS_DEPLOYED_ORIGIN:}

aws.cognito.region=${AWS_REGION:}
aws.cognito.user-pool-id=${AWS_USER_POOL:}

# DynamoDB configuration
aws.dynamodb.region=${AWS_REGION:us-east-1}
# Uncomment and set below if using DynamoDB Local
# aws.dynamodb.endpoint=http://localhost:8000

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

spring.security.filter.dispatcher-types=REQUEST,ERROR

aws.accessKey = ${YOUR_ACCESS_KEY}
aws.secretKey = ${YOUR_SECRET_ACCESS_KEY}